external:
  - scraper_conf:
      target: "https://vk.com:443"
      timeout: 3s
    analyzer_conf:
      alert_interval: 5m
      override_cn: ""
    scheduler_conf:
      timeout: 3s

  - scraper_conf:
      target: "https://expired.badssl.com:443"
      timeout: 1m
    analyzer_conf:
      alert_interval: 10m
      override_cn: "qq"
    scheduler_conf:
      timeout: 1m

internal:
  pool_size: 10
  min_scrape_interval: 10s

database:
  db_user: "postgres"
  db_pass: "postgres"
  db_host: "127.0.0.1"
  db_port: 5432
  db_name: "pgqdb"

queue:
  queue_name: "error_queue"
  event_name: "error"
  