scraper:
  - target: "https://vk.com"
    interval: 3s
    alert_interval: 5m
    override_cn: ""

  - target: "https://ya.ru"
    interval: 1m
    alert_interval: 10m
    override_cn: ""

scraper_internal:
  pool_size: 10
  min_scrape_interval: 10s