database:
  db_user: "postgres"
  db_pass: "postgres"
  db_host: "127.0.0.1"
  db_port: 5432
  db_name: "pgqdb"

telegram:
  bot_token: ""
  group_channel: "@***"
  messages_interval: "5s"

queue:
  queue_name: "error_queue"
  consumer_name: "telegram_bot_consumer"
