database:
  db_user: "postgres"
  db_pass: "postgres"
  db_host: "127.0.0.1"
  db_port: 5432
  db_name: "pgqdb"

telegram:
  bot_token: ""
  chat_id:
  messages_interval: "5s"

consumer:
  queue_name: "alerter_queue"
  batch_size: 10
