database:
  db_user: "postgres"
  db_pass: "postgres"
  db_host: "127.0.0.1"
  db_port: 5432
  db_name: "pgqdb"

consumer:
  queue_name: "certer_queue"
  batch_size: 10

producer:
  queue_name: "alerter_queue"

### Команда создать серты для кофига certer
#  openssl req -x509 -nodes -newkey rsa:2048 \
#  -keyout 127.0.0.1.key -out 127.0.0.1.crt \
#  -days 365 -subj "/CN=127.0.0.1" \
#  -addext "subjectAltName = IP:127.0.0.1"

certer:
  certificates:
    localhost:
      valid_for: "8760h"  # 1 год
      ca_cert: |
        -----BEGIN CERTIFICATE-----
        MIIFxzCCA6+gAwIBAgIUciYNG2SKggU51b7yx9uZXprQAd4wDQYJKoZIhvcNAQEL
        BQAwazELMAkGA1UEBhMCUlUxDzANBgNVBAgMBk1vc2NvdzEPMA0GA1UEBwwGTW9z
        Y293MRIwEAYDVQQKDAlNeUxvY2FsQ0ExDDAKBgNVBAsMA0RldjEYMBYGA1UEAwwP
        TXkgTG9jYWwgRGV2IENBMB4XDTI1MDUyMzE4NTYyOVoXDTM1MDUyMTE4NTYyOVow
        azELMAkGA1UEBhMCUlUxDzANBgNVBAgMBk1vc2NvdzEPMA0GA1UEBwwGTW9zY293
        MRIwEAYDVQQKDAlNeUxvY2FsQ0ExDDAKBgNVBAsMA0RldjEYMBYGA1UEAwwPTXkg
        TG9jYWwgRGV2IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArIlu
        D2asDEQrvhYQB+I7u5DKdvOE+od8T6m9GLE7eD/NW/d6+8m4DdHvBMQenuslTXaL
        5X2aM39n2FLjvEg3TVUG92zjzH5EOg8k7Y3VOF11yBvor4MwOPOhguInZ0BB7CrH
        XusuhUCp0LCltjqslHXpwP6ZHbp3Wc+jS8uIotECvhOfup13G+Ac4s2dYD9nj5ul
        56pzkmtdlauBd4V+Fnu57JHDShD7qbmgBec+fNpVbTuF7826x18WwnKg7me4fgK+
        kiEeqXMf7KH7R3WbdejEq7nvGjwlZ3Ejz2Xlyh8mHFsEZkMzv4xpn9/W7wF6Mr1F
        YBjJA1yI1AB+53ChONN2DRkkPjJJZHQMIUGikXBSKAKb0tBUGqHzVjqxpToDtLyG
        IXj78nnMxPeYhsxx6noLGausgzZKKM44UdleqSwVlDF7q4oMeVRRbTRF3mlK1/zz
        7mJ9ukjRf102YRW+kEZOwXFX+ay19vBhS5odMn4nbvFHZDaiMZn0F76REo+R47Nf
        XEM6siPr1gNazQMOpz25PT48aIH4H0z8lzzKk8dI1cyiFQOmTakHafI+Uln3xxcJ
        6ZneG1t6WqWkK5S0HUssO+a6Qt1jPot/OtW5IqYsFjzM3u/jYSY/MV2zUWmZ1hcT
        g14LzgtY1jRNhdBxOZsz8H2EJtUGNOSskonnU8ECAwEAAaNjMGEwDwYDVR0TAQH/
        BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFAVp7ieKBga84pkgSW9N
        abo8XMwXMB8GA1UdIwQYMBaAFAVp7ieKBga84pkgSW9Nabo8XMwXMA0GCSqGSIb3
        DQEBCwUAA4ICAQB7tR48IBOYdKgQ19zFlDGvcmeAGDrqPqIrd9u2qTQ+LwODnqzG
        vp3WwyQAcKttN57nKBw0Ab4zLG5AP/NUZEx+7+0zqjAaWwbddwb3nww7jdWKN/9l
        xusx6/yNSnx1KG3/F31DqnNXe6rXlmO3GO6a9Tt+Cn3xp1ugaz7YP8kOiXT60yCE
        aS/1/6lVDXgcYWj0wCCCqlsmk+TKaZeSwTh+QVWvJCdkLWbl8d2W/rH06ToDYpjz
        QE6WOWt/zs2AP5wtuWUyqfzcWacbmdq4W5ItI/fDhRtx5Qda9/0dJl55MhKRLba8
        JR13c3xC3/vwoeLcVOYxhpZeNZhlMP3RfTFVaauZPmDuFHtPbr9W+rWV2CVMn1Kl
        dwPbQDlUKqXxdiNaoV0As1a404zJs7WGEPQFpH4ja5C6kwI3mT5nsRyrce7RfU7M
        kmu3iCR/WRVJiDSzDLaKgNvBJ7m4g+fWAEvAdCI3424v3GOAY+S8yG5elX2t2VXB
        5QrlkRBTZHi8HQ/VYRvX4L6pAWy46uINKFbvCzlT97jZinYW1IjGK64MAHmXPzCA
        JcReFGU0YiQzovGAi9V9atxzO//83w9SG8qCF7f0xamiWby+W/ySbXq0ObF7NrAj
        WvW1a2E9e7gS8yeeVxx1sjXg0rdr1FKPtDxWvfvuEawFbhfeKefw6gWeFQ==
        -----END CERTIFICATE-----

      ca_key: |
        -----BEGIN PRIVATE KEY-----
        MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCsiW4PZqwMRCu+
        FhAH4ju7kMp284T6h3xPqb0YsTt4P81b93r7ybgN0e8ExB6e6yVNdovlfZozf2fY
        UuO8SDdNVQb3bOPMfkQ6DyTtjdU4XXXIG+ivgzA486GC4idnQEHsKsde6y6FQKnQ
        sKW2OqyUdenA/pkdundZz6NLy4ii0QK+E5+6nXcb4BzizZ1gP2ePm6XnqnOSa12V
        q4F3hX4We7nskcNKEPupuaAF5z582lVtO4XvzbrHXxbCcqDuZ7h+Ar6SIR6pcx/s
        oftHdZt16MSrue8aPCVncSPPZeXKHyYcWwRmQzO/jGmf39bvAXoyvUVgGMkDXIjU
        AH7ncKE403YNGSQ+MklkdAwhQaKRcFIoApvS0FQaofNWOrGlOgO0vIYhePvyeczE
        95iGzHHqegsZq6yDNkoozjhR2V6pLBWUMXurigx5VFFtNEXeaUrX/PPuYn26SNF/
        XTZhFb6QRk7BcVf5rLX28GFLmh0yfidu8UdkNqIxmfQXvpESj5Hjs19cQzqyI+vW
        A1rNAw6nPbk9PjxogfgfTPyXPMqTx0jVzKIVA6ZNqQdp8j5SWffHFwnpmd4bW3pa
        paQrlLQdSyw75rpC3WM+i3861bkipiwWPMze7+NhJj8xXbNRaZnWFxODXgvOC1jW
        NE2F0HE5mzPwfYQm1QY05KySiedTwQIDAQABAoICAA5jSPxrjFAbDLdFpXlU1DSa
        WMnl2YpfSz5k6hYRrIME9gnz56twyUKMxcT02lVYCFSu/LBK4rWl65naYq+YKZVv
        MF0odVAfnO6nBeYx8EyKnaht7F/bfaVYKrkshQrrDLxGHnlTvR3DVE3o9y6ssqjQ
        MumjSY81Nh/1DNnkm4yxR4xkfErOeAjo7du7eALXUrpi6Uk5+XiFr8iMBGg8R3UW
        RP09dAa8hxICnt2zKI62kc5huvPyCN/4leAp+THcUCIg9jWfIayRg0FjSh4tyGSj
        IChuYUojpx5azNjOF2UdJxtQ+ztQYhO4gLPicYzdh4xM5IjElFmtiSL9thd0eNsu
        WJLoORs3A39o3/0/lro9k6AEzYXQbMDBo0fwbPyhs+KqZWCf/FIcorRl+s1h7W4k
        mV7jS0CRUWA1+HUuB1maZ/j/8rfpeW3mwI+uTOuBhPSQCwCaPKNA08pguFgiloe3
        VEAnP/RmnnNt561XGIpRRbKiPGYYmYK0Gp+d2DYvxY7lmMJDd/3LKqc6WdsNb95Y
        iQJQP1MChfsIe2EIp25Bf6b4boQEqs3LXvOweifwQ8jn/zXtXI2RrEmJ7bx6iz0X
        SAL8mXN5UpZe03Ks+jJISaWpuWKOrHRFtPF7Rye2Qk1mFwA1pnv6wBwp7uRUxe/s
        jKMiI1fyNgPsFlKcyut5AoIBAQDTztrWoyVZaPBgrPMDRr8FjJu8hKIh2PdmQplu
        vhgOVugJkaQ+JCmkT+vYsJxfvTxJ256yKR2N4a/EpZYdd2gNfzVkkNDEWdJUtf0r
        7BqGizIVt/cS1rJuyad1YQO6lRS24RVLCcwGj6LXX8eZiTvFQaCxzgQnVZdg8Ktj
        i7VEN23qSLGDBiol6japt8erotVt5xUYM6wfoL/oda7TG8/7AcZOtclxMI8t4qLm
        Ks5levukS08mufym4+PuibyT696riLGQ5cnEVzgP49krSgDNrhjukPkm/ZhA4mZ9
        CH7nYEXoOVVz34hL5uIzTyHKuHU8GwkrI6KJZlLES4+11PjpAoIBAQDQiQMWU0m7
        v5RWqm7jbsWY5nZHXXdJj8TkRNONbQ1jHL3iNhLSZf/jOhuTYc5p7WvCI+AxjEG+
        czvHzeZp+vUJCUqA+bvOY4MOUUWEkPplSelYRJiIIJxcjh6UJRLtNAsInghD7Z4A
        y/8S2NVKWsjsyWZsuPFHAevboRivRnNaIeVQ6CixlxHUnJ4RUF8wcLINHwDOcyZi
        VH06LH1LUxYsfBBxPzbvbtqqiWXwr70zQ3UWNqWGTnODzVvqxnMKs9+gSLHD/SP9
        Y7SVNAMEpyHGsf+nXHsdpxUwXt+/TZyyUdf5YuMGK3hVI0YEZh3qM3Azt+DfuCw0
        oG7uH4ETP70ZAoIBACywxLPtEIBhB/ceBth2IPAGzwVj5uHFac4F12HqciD0bVk3
        hbQm5TJqOpUqDpSU1RewYzesPTQmnnObjKUDAM14PcfOVn5XhW2iSJzv4FjrHdI/
        Ur6C1ntRySeXJLZFpm0/6MJAevAXdoCDERZwQlBInKNnmLDD+oDVxxPl8oVGPMbm
        N64xqsr9NDNzN4obfXUHAQhuPq8dt+BQlGauw59urG0HJk3ftRY1b7Go7ouy+02b
        JkRBkfGUvA8kuMltRzpiSTUNhxkKXiXcKYJcxvae+Vu88xUrBOkL3BwdosknIxjw
        n/sm+xcozCmPVM31Rac8/R5BEpZzJJuOZfAz06ECggEAaDFdCoWY3KcPTfIgL6DE
        N+5GgMfRdz7PSKKe9RXcz32n3mPYKanvHbCF4LDIuqJ26eyU8wy6OJdI8j8Ndjx+
        vAIZaLHexXNxIvE2g9MQWRWB8qlrcPCiT5hu7ORNPZl4PdkAFjiebpV+oAMZJuqP
        Y8gJVh9d5nWuS/GE7OaNciZndnJZCsqJjSqny8zVktVsESRBeeWM8yp122ApRj6A
        YL+oU30bTKydswGtnoGgTgHRecTaFW4TR3KPD5ISHvHatTI9J8jOd6eercHsFCIR
        vT5ol02c8ibublmo/+OefHZqK9/dwNJtcFSMglwnbEJBOIYSZJWX+L+ETZQOIPkC
        2QKCAQApQJRV/HVmxTHYqpll+V6LH2yG0myxQvjj3sGIOk+81lh0J/5fHe78EFsu
        MZoh3km0+p6J6Hkhbe1qA8EX2hL32DJyjOtQe2IPBeN8RPSkhAzBb41JFpkYZCKX
        UF7pNnRC5Co5lz75uFhaR70CAWyNMt00CKMx6wJdx8hAXwyD2MSDkuM59Kf041jC
        9tgfEN4k5tZFMO4dcpkqnrac9jOGSvo5M10yp4MgYmw4FKVmTMfvWQURTO3ojyft
        srJo3a69O1VwtuLJCxtqtOQKzIQxjMhdurCYosPZ/OcCTQJvQBZsH3jXtjabm+13
        zIhkBACRhVvlshAhSld+TaB84dTa
        -----END PRIVATE KEY-----


setter:
  sets:
    localhost:
      path: "/app/certs/"
      type: ""

scheduler:
  interval: 10s