database:
  db_user: "postgres"
  db_pass: "postgres"
  db_host: "postgres"
  db_port: 5432
  db_name: "pgqdb"

consumer:
  queue_name: "certer_queue"
  batch_size: 10

producer:
  queue_name: "alerter_queue"

certer:
  certificates:
    expired.badssl.com:
      organization: ""
      valid_for: "8760h"  # 1 год
      ca_cert: |
        -----BEGIN CERTIFICATE-----
        MIIDXTCCAkWgAwIBAgIJALbU5vV... 
        -----END CERTIFICATE-----
      ca_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEA... 
        -----END RSA PRIVATE KEY-----

setter:
  sets:
    expired.badssl.com:
      path: "/app/certs/example.com"
      type: ""

scheduler:
  interval: 10s